# Generated by Django 3.1.5 on 2021-03-08 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0001_initial'),
        ('releases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='description',
        ),
        migrations.AlterField(
            model_name='release',
            name='build',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builds.build'),
        ),
    ]
