# Generated by Django 3.1.5 on 2021-01-08 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20210108_1311'),
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='environmentvariable',
            name='is_unique',
        ),
        migrations.AddConstraint(
            model_name='environmentvariable',
            constraint=models.UniqueConstraint(fields=('app', 'key'), name='envvar_is_unique'),
        ),
        migrations.AddField(
            model_name='process',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.app'),
        ),
        migrations.AddConstraint(
            model_name='process',
            constraint=models.UniqueConstraint(fields=('app', 'key'), name='process_is_unique'),
        ),
    ]
