# Generated by Django 3.1.5 on 2021-01-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainbinding',
            name='cname',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='domainbinding',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='domainbinding',
            constraint=models.UniqueConstraint(fields=('app', 'cname', 'domain'), name='domain_is_unique'),
        ),
    ]
