/**
 * Hippo.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Revision } from './revision';
import { DomainEvent } from './domainEvent';
import { Channel } from './channel';

export interface App {
    created?: string;
    createdBy?: string | null;
    lastModified?: string;
    lastModifiedBy?: string | null;
    id?: string;
    name?: string | null;
    storageId?: string | null;
    readonly channels?: Array<Channel> | null;
    readonly revisions?: Array<Revision> | null;
    domainEvents?: Array<DomainEvent> | null;
}
