/**
 * Hippo.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AppChannelSummary } from './appChannelSummary';


export interface AppDto { 
    id: string;
    name: string;
    storageId: string;
    description: string;
    channels: Array<AppChannelSummary>;
}

