/**
 * Hippo.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AppChannelListItem } from './appChannelListItem';

export interface AppItem {
    name: string;
    id: string;
    storageId: string;
    description?: string | null;
    channels: Array<AppChannelListItem>;
}
