/**
 * Hippo.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CertificateItem } from './certificateItem';


export interface CertificateItemPage { 
    items?: Array<CertificateItem> | null;
    totalItems?: number;
    pageIndex?: number | null;
    pageSize?: number | null;
    readonly isLastPage?: boolean | null;
}

