/**
 * Hippo.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RevisionItem } from './revisionItem';
import { ChannelRevisionSelectionStrategy } from './channelRevisionSelectionStrategy';
import { CertificateItem } from './certificateItem';
import { AppSummaryDto } from './appSummaryDto';
import { EnvironmentVariableDto } from './environmentVariableDto';


export interface ChannelItem { 
    id: string;
    appId: string;
    name: string;
    domain: string;
    revisionSelectionStrategy: ChannelRevisionSelectionStrategy;
    activeRevision?: RevisionItem;
    rangeRule?: string | null;
    certificate?: CertificateItem;
    environmentVariables: Array<EnvironmentVariableDto>;
    appSummary?: AppSummaryDto;
}

