/**
 * Hippo.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Revision } from './revision';
import { ChannelRevisionSelectionStrategy } from './channelRevisionSelectionStrategy';
import { EnvironmentVariableDto } from './environmentVariableDto';
import { Certificate } from './certificate';


export interface ChannelDto { 
    id: string;
    appId: string;
    name: string;
    domain: string;
    revisionSelectionStrategy: ChannelRevisionSelectionStrategy;
    activeRevision?: Revision;
    rangeRule?: string | null;
    certificate?: Certificate;
    environmentVariables: Array<EnvironmentVariableDto>;
}

