/**
 * Hippo.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChannelRevisionSelectionStrategy } from './channelRevisionSelectionStrategy';


export interface CreateChannelCommand { 
    appId: string;
    name: string;
    domain?: string | null;
    revisionSelectionStrategy: ChannelRevisionSelectionStrategy;
    rangeRule?: string | null;
    activeRevisionId?: string | null;
    certificateId?: string | null;
}

