/**
 * Hippo.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DomainEvent } from './domainEvent';
import { Channel } from './channel';


export interface EnvironmentVariable { 
    created?: string;
    createdBy?: string | null;
    lastModified?: string;
    lastModifiedBy?: string | null;
    id?: string;
    key?: string | null;
    value?: string | null;
    channelId?: string;
    channel?: Channel;
    domainEvents?: Array<DomainEvent> | null;
}

