/**
 * Hippo.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Revision } from './revision';
import { DomainEvent } from './domainEvent';

export interface RevisionComponent {
    created?: string;
    createdBy?: string | null;
    lastModified?: string;
    lastModifiedBy?: string | null;
    id?: string;
    source?: string | null;
    name?: string | null;
    route?: string | null;
    channel?: string | null;
    type?: string | null;
    revisionId?: string;
    revision?: Revision;
    domainEvents?: Array<DomainEvent> | null;
}
