/**
 * Hippo.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { App } from './app';
import { RevisionComponent } from './revisionComponent';
import { DomainEvent } from './domainEvent';

export interface Revision {
    created?: string;
    createdBy?: string | null;
    lastModified?: string;
    lastModifiedBy?: string | null;
    id?: string;
    revisionNumber?: string | null;
    description?: string | null;
    appId?: string;
    app?: App;
    readonly components?: Array<RevisionComponent> | null;
    domainEvents?: Array<DomainEvent> | null;
}
