# Generated by Django 3.1.5 on 2021-01-08 13:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='created_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='app',
            old_name='last_updated',
            new_name='updated',
        ),
        migrations.RemoveField(
            model_name='app',
            name='id',
        ),
        migrations.AddField(
            model_name='app',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
    ]
