# This is a temporary measure to pre-build the dev container image until GH support for codespaces pre-build is enabled.
# If the contents of the docker file change then the image version env value here (DEVCONTAINER_VERSION) and in the devcontainer.json file should be changed.
name: Build devcontainer image

on:
  push:
    branches: [ main ]

jobs:
  release:
    name: Push devcontainer/codespaces image to GitHub Package Registry
    runs-on: ubuntu-latest
    env:
      DEVCONTAINER_VERSION: v1.0.1
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}-dev
          tags: |
            type=raw,value=${{ env.DEVCONTAINER_VERSION }}
            type=sha,priority=2
          flavor: |
            latest=true
    
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          file: .devcontainer/Dockerfile
          context: .devcontainer
          build-args: |
            VARIANT : 5.0
            NODE_VERSION: lts/*
            HIPPO_VERSION: v0.9.0
            BINDLE_VERSION: v0.6.0
            WAGI_VERSION: v0.4.0
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}