# Generated by Django 3.1.5 on 2021-02-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envvars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='environmentvariable',
            name='envvar_is_unique',
        ),
        migrations.RenameField(
            model_name='environmentvariable',
            old_name='app',
            new_name='owner',
        ),
        migrations.AddConstraint(
            model_name='environmentvariable',
            constraint=models.UniqueConstraint(fields=('owner', 'key'), name='envvar_is_unique'),
        ),
    ]
